# Generated by Django 5.0.14 on 2026-03-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_breakdown',
            field=models.JSONField(blank=True, null=True, verbose_name='AI: Разбивка на подзадачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_complexity',
            field=models.CharField(blank=True, choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], max_length=20, null=True, verbose_name='AI: Сложность'),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_estimated_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='AI: Оценка времени (часы)'),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_reasoning',
            field=models.TextField(blank=True, null=True, verbose_name='AI: Обоснование оценки'),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=20, null=True, verbose_name='AI: Уровень риска'),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_suggested_level',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], max_length=20, null=True, verbose_name='AI: Рекомендуемый уровень'),
        ),
    ]
