# Generated by Django 5.0.14 on 2026-05-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_ai_breakdown_task_ai_complexity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='comment_attachments/', verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='text',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
