# Generated by Codex

import django.db.models.deletion
import tasks.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('status_changed', 'Статус изменён'), ('assignee_changed', 'Исполнитель изменён'), ('comment_added', 'Комментарий добавлен'), ('task_created', 'Задача создана'), ('task_updated', 'Задача обновлена'), ('task_archived', 'Задача архивирована')], max_length=40)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task')),
            ],
            options={
                'verbose_name': 'История задачи',
                'verbose_name_plural': 'История задач',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='comment_attachments/', validators=[tasks.validators.validate_attachment_file], verbose_name='Вложение'),
        ),
    ]
